
<?php foreach($resultarticles as $key => $value): ?>
    <article>
        <h2> <?= $value['titre'];?> </h2>
        <?php if (($value['imageentete'] != NULL) || ($value['imageentete'] != "")): ?> 
        <img src=" <?= IMGARTICLE.$value['imageentete']?> "/>
   		<?php endif; ?>
        <p> <?= $value['contenu'];?> </p> 
        <h3> Ecrit par <a href="blog/admin/detailsUser.php?id=<?= $value['idutilisateurs'];?>"> <span> <?= $value['pseudo'];?> </span> </a>, le <?= $value['date'];?> </h3>
        <small> Article numéro <?= $value['idarticles'];?> </small>
        <button> <a href="comArticle.php?id=<?= $value['idarticles'];?>"> Lache tes com'z </a> </button>
    </article>
<?php endforeach ?>
